/**
 * oidc-client-ts UserManager — OIDC Authorization Code + PKCE + DPoP
 *
 * The library's `IndexedDbDPoPStore` is the single source of truth for the
 * DPoP keypair. It hard-codes database name "oidc" and store name "dpop"
 * (constructor args are ignored as of v3.5.0).
 *
 * Storage layout in IndexedDB:
 *   database: "oidc"
 *   store:    "dpop"
 *   key:      <client_id>           (e.g. "react-dpop")
 *   value:    DPoPState { keys: CryptoKeyPair, nonce?: string }
 *
 * The library auto-generates a P-256 ECDSA non-extractable keypair on first
 * use (via `OidcClient.generateDPoPJkt()`) and reuses it for the lifetime of
 * the persisted session. Both:
 *   - the library's own token-endpoint proofs (sign-in + silent renew), and
 *   - our axios interceptor's resource-server proofs
 * read the SAME keypair from this store, so cnf.jkt binding holds end-to-end.
 */

import {
  UserManager,
  type UserManagerSettings,
  type User,
  IndexedDbDPoPStore,
} from 'oidc-client-ts';

// Fail fast in production when env vars are missing.
function requireEnv(name: string, devFallback: string): string {
  const value = (import.meta.env[name] as string | undefined) ?? '';
  if (value) return value;
  if (import.meta.env.PROD) {
    throw new Error(
      `[OIDC] Missing required environment variable ${name} in production build.`,
    );
  }
  return devFallback;
}

const AUTHORITY = requireEnv('VITE_IDENTITY_SERVER_AUTHORITY', 'https://localhost:5001');
const CLIENT_ID = requireEnv('VITE_OIDC_CLIENT_ID', 'react-dpop');
const REDIRECT_URI = requireEnv('VITE_OIDC_REDIRECT_URI', 'http://localhost:5173/callback');
const POST_LOGOUT_REDIRECT_URI = requireEnv('VITE_OIDC_POST_LOGOUT_URI', 'http://localhost:5173');

// Single shared DPoP store — same instance used by axios interceptor.
export const dpopStore = new IndexedDbDPoPStore();

let _manager: UserManager | null = null;

export function getUserManager(): UserManager {
  if (_manager) return _manager;

  const settings: UserManagerSettings = {
    authority: AUTHORITY,
    client_id: CLIENT_ID,
    redirect_uri: REDIRECT_URI,
    post_logout_redirect_uri: POST_LOGOUT_REDIRECT_URI,
    response_type: 'code',
    scope: 'openid profile retail-api offline_access',
    automaticSilentRenew: true,

    // DPoP: oidc-client-ts v3 native support. Library lazily generates a
    // P-256 keypair on first signinRedirect / silent renew if the store is
    // empty, and persists DPoPState (keys + nonce) against client_id.
    dpop: {
      bind_authorization_code: true,
      store: dpopStore,
    },
  };

  _manager = new UserManager(settings);

  _manager.events.addSilentRenewError((err) => {
    console.error('[OIDC] Silent renew error:', err);
  });

  return _manager;
}

/**
 * Read the persisted DPoP keypair (lazy-generated by the library on first
 * signinRedirect). Returns null if the user has never logged in.
 */
export async function getDPoPKeyPair(): Promise<CryptoKeyPair | null> {
  try {
    const state = await dpopStore.get(CLIENT_ID);
    return state?.keys ?? null;
  } catch {
    return null;
  }
}

/**
 * Remove the persisted DPoP keypair. Call on logout so the next session
 * starts with a fresh key — defense in depth even though revoked tokens
 * cannot be replayed.
 */
export async function clearDPoPKeyPair(): Promise<void> {
  try {
    await dpopStore.remove(CLIENT_ID);
  } catch {
    // Ignore — store may be empty already.
  }
}

export async function getUser(): Promise<User | null> {
  return getUserManager().getUser();
}

export async function signinRedirect(): Promise<void> {
  await getUserManager().signinRedirect();
}

export async function signinCallback(): Promise<User> {
  return getUserManager().signinRedirectCallback();
}

export async function signoutRedirect(): Promise<void> {
  await getUserManager().signoutRedirect();
}

/** Exchange refresh token for a new DPoP-bound access token. */
export async function silentRenew(): Promise<User | null> {
  return getUserManager().signinSilent();
}
